### ISSUE TITLE
Tag filtering isn't working correctly

### ISSUE THREAD

**Issue by ktechmidas** [linode/linode_api4-python#156]
Unsure what's causing this, I've had a quick look but nothing jumps out.

Consider this code, which works and pulls any instances which have the "core" tag

> s = client.linode.instances(Instance.tags == "core")

According to [the docs](https://linode-api4.readthedocs.io/en/latest/linode_api4/objects/filtering.html) I should be able to use any boolean comparisons, and it gives an example of it working with region, however this doesn't appear to be working with tags, it is complaining about the tag not being a string, which seems silly as it works just fine if I search *for* it, just not *excluding* it.

> s = client.linode.instances(Instance.tags != "core")

-----

`Traceback (most recent call last):
  File "lin.py", line 34, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "lin.py", line 31, in main
    s = client.linode.instances(Instance.tags != "core")
  File "/usr/local/lib/python2.7/dist-packages/linode_api4/linode_client.py", line 65, in instances
    return self.client._get_and_filter(Instance, *filters)
  File "/usr/local/lib/python2.7/dist-packages/linode_api4/linode_client.py", line 1222, in _get_and_filter
    return self._get_objects(obj_type.api_list(), obj_type, filters=parsed_filters)
  File "/usr/local/lib/python2.7/dist-packages/linode_api4/linode_client.py", line 895, in _get_objects
    response_json = self.get(endpoint, model=model, filters=filters)
  File "/usr/local/lib/python2.7/dist-packages/linode_api4/linode_client.py", line 911, in get
    return self._api_call(*args, method=self.session.get, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/linode_api4/linode_client.py", line 885, in _api_call
    raise ApiError(error_msg, status=response.status_code, json=j)
linode_api4.errors.ApiError: 400: tags must be of type String;`

**Comment by Dorthu** [comment]
Filtering tags with `!=` (or other operators) sends a filter header like this:

```
{"tags": {"+ne": "demo"}}
```

That _should_ work.  Sending that same header through `curl` causes the same error.  I believe this is an API error, so I logged it in our internal bug tracker and will update this issue when it's addressed.

**Comment by Dorthu** [comment]
Sorry this took so long to get back to.  This was fixed upstream, and I submitted one more change here to make it actually work.  The change was shipped in version 2.3.3

**Comment by ktechmidas** [comment]
No problem! Thank you very much for fixing it, appreciate it :)
