### ISSUE TITLE
Instance.ips raises TypeError

### ISSUE THREAD

**Issue by enbeec** [linode/linode_api4-python#287]
### Package

5.4.0

### Expected Behavior

Use the `Instance.ips` attribute to get networking info.

### Actual Behavior

A `TypeError` on trying to access `Instance.ips`

### Steps to Reproduce

`client.linode.instances()[0].ips`

### Error Output

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/val/linode-scripts/venv/lib/python3.10/site-packages/linode_api4/objects/base.py", line 176, in __getattribute__
    return object.__getattribute__(self, name)
  File "/home/val/linode-scripts/venv/lib/python3.10/site-packages/linode_api4/objects/linode.py", line 468, in ips
    pools = [IPv6Pool(self._client, result["ipv6"]["global"]["range"])]
TypeError: list indices must be integers or slices, not str
```

**Comment by enbeec** [comment]
Use case is creating an up-to-date `rc.conf` networking config on a manually installed FreeBSD Linode.

**Comment by enbeec** [comment]
Just saw the PR for this!
